resources:
- name: main
  type: git
  source:
    uri: https://github.com/akipriyadarshi/Maven_Assignment
    branch: main
- name: dev
  type: git
  source:
    uri: https://github.com/akipriyadarshi/Maven_Assignment
    branch: dev
 
jobs:
  - name: test
    public: true

    plan:
      - get: main
        trigger: true
      - task: mvn-test
        file: "multi/concourse_ci/tasks/test.yml"
jobs:
  - name: compile
    public: true

    plan:
      - get: dev
        trigger: true
      - task: mvn-compile
        file: "multi/concourse_ci/tasks/compile.yml"
